### ISSUE TITLE
Dropdown for courses are arranged differently

### ISSUE THREAD

**Issue by kaz-paolo** [xkaze09/dpsm-website#9]
![a5a06381-e602-429d-a2b3-c1516254639a](https://github.com/xkaze09/dpsm-website/assets/100914115/b3c87232-7f5b-4582-9020-137ee8039968)

**Comment by xkaze09** [comment]
[Fixed course dropdown arrangement ](https://github.com/xkaze09/dpsm-website/commit/d9b55cfe38c7af74d39c5e8d21ddced8b102ea2b) by applying the following changes below to pages about.html, statistics.html, and applied-mathematics.html.

              <a class="dropdown-item" href="./applied-mathematics.html">B.S. in Applied Mathematics</a>
              <a class="dropdown-item" href="./computer-science.html">B.S. in Computer Science</a>
              <a class="dropdown-item" href="./statistics.html">B.S. in Statistics</a>

Sorted alphabetically.
