### ISSUE TITLE
Prospectus table per course does not load properly on mobile

### ISSUE THREAD

**Issue by xkaze09** [xkaze09/dpsm-website#98]
- The prospectus table does not load < 400px, specifically iPhone-sized screen sizes.
- F12 dev tools may show it just fine

See image below:
![image](https://github.com/xkaze09/dpsm-website/assets/47445339/c37ce003-0ca4-42d0-b585-3d64cece8998)

**Comment by xkaze09** [comment]
New images below. From MacBook & another iPhone device

<details>![image](https://github.com/xkaze09/dpsm-website/assets/47445339/e1d9d58f-86cc-48d5-a9fd-73e11561ae92)</details>
<details>![image](https://github.com/xkaze09/dpsm-website/assets/47445339/eb5c210a-3820-4362-a5ac-1344b877a478)</details>

**Comment by ezerssss** [comment]
> * The prospectus table does not load < 400px, specifically iPhone-sized screen sizes.
> * F12 dev tools may show it just fine
> 
> See image below: ![image](https://private-user-images.githubusercontent.com/47445339/309778084-c37ce003-0ca4-42d0-b585-3d64cece8998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzA5NzYsIm5iZiI6MTcwOTczMDY3NiwicGF0aCI6Ii80NzQ0NTMzOS8zMDk3NzgwODQtYzM3Y2UwMDMtMGNhNC00MmQwLWI1ODUtM2Q2NGNlY2U4OTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzMTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzQ0OTc2ODEzY2ZkOWNhMjQxYjY5YmVhOTMwYzI2NzMyZjJmMzU3NTk5Y2IyNDU3NzczNDEzMzhhMTVkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUF1osL1b_M0ixbn0NqPXSMt3v4wqeX_sAeUA3YHeG8)

Can you open the console to check if there may be errors? seems that the JSON file is not loaded thus not rendering the rows. Might be a fetching issue that iOS is preventing.

**Comment by xkaze09** [comment]
> > * The prospectus table does not load < 400px, specifically iPhone-sized screen sizes.
> > * F12 dev tools may show it just fine
> > 
> > See image below: ![image](https://private-user-images.githubusercontent.com/47445339/309778084-c37ce003-0ca4-42d0-b585-3d64cece8998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MzA5NzYsIm5iZiI6MTcwOTczMDY3NiwicGF0aCI6Ii80NzQ0NTMzOS8zMDk3NzgwODQtYzM3Y2UwMDMtMGNhNC00MmQwLWI1ODUtM2Q2NGNlY2U4OTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDEzMTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzMzQ0OTc2ODEzY2ZkOWNhMjQxYjY5YmVhOTMwYzI2NzMyZjJmMzU3NTk5Y2IyNDU3NzczNDEzMzhhMTVkNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NUF1osL1b_M0ixbn0NqPXSMt3v4wqeX_sAeUA3YHeG8)
> 
> Can you open the console to check if there may be errors? seems that the JSON file is not loaded thus not rendering the rows. Might be a fetching issue that iOS is preventing.

Turns out that /data.json was not being loaded properly.

Fixed it by fetching it asynchronously and only then will generateProspectusTable be called. 

For more information, see latest commit at #99. 

Issue will now be marked as resolved, should there be no additional issues.
